// <auto-generated/>
#nullable enable
#if TSR_DI_ATTRIBUTES_PACKAGE || TSR_DI_NEED_INTERNAL_ATTRIBUTE
using System;
namespace tsr_di;

#if TSR_DI_ATTRIBUTES_PACKAGE
public partial class ServiceResolverAttribute;
public partial class ServiceClassAttribute;
public partial class ServiceFunctionAttribute;
#else
[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)] internal partial class ServiceResolverAttribute;
[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)] internal partial class ServiceClassAttribute;
[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)] internal partial class ServiceFunctionAttribute;
#endif
#if TSR_DI_ATTRIBUTES_PACKAGE
public
#else
 internal 
#endif
enum LifeTime
{
    Singleton,
    Scoped,
    Transient,
}
#if TSR_DI_ATTRIBUTES_PACKAGE
public
#else
 internal 
#endif
enum SharingMode
{
    Shared,
    IsolatePerService,
}

[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
partial class ServiceResolverAttribute : Attribute;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
partial class ServiceClassAttribute : Attribute
{
    public LifeTime LifeTime { get; set; } = LifeTime.Transient;
    public SharingMode SharingMode { get; set; } = SharingMode.Shared;
    public string? Name { get; set; } = null;
}

[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
partial class FromNamedAttribute(string Name): Attribute
{
    public string Name { get; init; } = Name;
}

[AttributeUsage(AttributeTargets.Method , AllowMultiple = false)]
partial class ServiceFunctionAttribute : Attribute
{
    public Type? ServiceType { get; set; } = null;
    public string? ServiceName { get; set; } = null;
    public string? Name { get; set; } = null;
}

#endif
