// <auto-generated/>
#nullable enable
#pragma warning disable IDE0079
#pragma warning disable IDE0059
#pragma warning disable CS8625
#pragma warning disable CS8510
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading;
using {0}.AutoDefined;

namespace {0};
static partial class {1}
{{
[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
private interface IResolver<T>
{{
    T Resolve( FieldStore store, ServiceKey key);
    IEnumerable<T> ResolveAll(FieldStore store);
}}

private partial class InnerResolver;

static readonly InnerResolver inner = new ();

[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
public static T Resolve<T>(ServiceKey  key= ServiceKey.None) => ((IResolver<T>)inner).Resolve(new FieldStore(), key);

[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
public static IEnumerable<T> ResolveAll<T>() => ((IResolver<T>)inner).ResolveAll(new FieldStore());

{2}

}}
