// <auto-generated/>
#nullable enable
#pragma warning disable IDE0079
#pragma warning disable IDE0059
#pragma warning disable CS8625
#pragma warning disable CS8510
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using {0}.AutoDefined;
namespace {0};

static partial class {1}
{{
[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
private class InnerResolver<T>
{{
public static Func<FieldStore, ServiceKey, T> Resolve;
public static Func<FieldStore, IEnumerable<T>> ResolveAll;
static InnerResolver()
{{
var tp = typeof(T);
if (false) {{  }}
  {2}
else {{
    Resolve = (_,_) => throw new UnreachableException();
    ResolveAll = (_) => throw new UnreachableException(); 
}}
}}
}}

[MethodImpl(MethodImplOptions.AggressiveInlining)] [System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
public static T Resolve<T>(ServiceKey  key= ServiceKey.None) => InnerResolver<T>.Resolve(new FieldStore(), key);

[MethodImpl(MethodImplOptions.AggressiveInlining)] [System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
public static IEnumerable<T> ResolveAll<T>() => InnerResolver<T>.ResolveAll(new FieldStore());

{3}

}}
