// <auto-generated/>
#nullable enable
#pragma warning disable IDE0079
#pragma warning disable IDE0059
#pragma warning disable CS8625
#pragma warning disable CS8510
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading;
using {0}.AutoDefined;

namespace {0};
static partial class {1}
{{
[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
private interface IResolver<T>
{{
    T Resolve( ref ResolveContext store, ServiceKey key);
    ReadOnlyCollection<T> ResolveAll( ref ResolveContext store);
}}

private partial class InnerResolver;

static readonly InnerResolver inner = new ();

[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static T Resolve<T>(ServiceKey key = ServiceKey.None)
{{
        ResolveContext localStore = default;
        return ((IResolver<T>)inner).Resolve(ref localStore, key);
}}

[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static ReadOnlyCollection<T> ResolveAll<T>()
{{
        ResolveContext localStore = default;
        return ((IResolver<T>)inner).ResolveAll(ref localStore);
}}

{2}

}}
