// <auto-generated/>
#nullable enable
#pragma warning disable IDE0079
#pragma warning disable IDE1006
#pragma warning disable CA1822
#pragma warning disable CS8625
using System;
using System.Threading;
using {0}.AutoDefined;
namespace {0};
static partial class {1}
{{
[System.CodeDom.Compiler.GeneratedCode("tsr-di", null)]
private class FieldStore {{
{2}
}}
}}
